version: '3.8'

services:

  postgres:
    image: postgres:14

    container_name: postgres_db

    environment:
      POSTGRES_DB: employee_access_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  app:
    build: .

    container_name: employee_access_app

    ports:
      - "8090:8090"

    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_access_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres